# CloudOS Dashboard Setup Script
# Usage: cloudos module add dashboard

dashboard_setup() {
  local module_dir="${CLOUDOS_ROOT}/modules/dashboard"
  local data_dir="${module_dir}/data/homer"
  
  log_step "Setting up Dashboard module (Homer)"

  mkdir -p "${data_dir}/assets"

  # Auto-discover running services from Docker labels
  log_info "Scanning running services..."
  
  # Get all CloudOS containers with their labels
  local services_json
  services_json=$(docker ps --filter "label=cloudos.module" --format '{{.Names}}|{{.Label "cloudos.service"}}|{{.Label "cloudos.title"}}|{{.Label "cloudos.description"}}|{{.Label "cloudos.icon"}}' 2>/dev/null)
  
  # Build Homer config
  local homer_services=""
  
  while IFS='|' read -r name svc title desc icon; do
    [ -z "$name" ] && continue
    
    # Determine URL and icon
    local url=""
    local default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/${svc}.svg"
    
    # Map service names to URLs and icons
    case "$svc" in
      "nextcloud")
        url="http://100.79.173.91:8081"
        default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/cloud.svg"
        ;;
      "searxng")
        url="http://100.79.173.91:4000"
        default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/search.svg"
        ;;
      "meilisearch")
        url="http://100.79.173.91:7700"
        default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/database.svg"
        ;;
      "netdata")
        url="http://100.79.173.91:9001"
        default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/chart-bar.svg"
        ;;
      "cadvisor")
        url="http://100.79.173.91:8082"
        default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/chart-line.svg"
        ;;
      "caddy")
        url="http://100.79.173.91:80"
        default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/cloud.svg"
        ;;
      "authentik-server")
        url="http://100.79.173.91:80/auth/"
        default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/lock.svg"
        ;;
      "homer")
        url="http://100.79.173.91:8080"
        default_icon="https://cdn.jsdelivr.net/npm/@homer/icons/home.svg"
        ;;
      *)
        url="http://100.79.173.91"
        ;;
    esac
    
    [ -z "$icon" ] && icon="$default_icon"
    [ -z "$title" ] && title="$svc"
    [ -z "$desc" ] && desc="$svc service"
    
    homer_services="${homer_services}
    - name: \"${title}\"
      logo: \"${icon}\"
      subtitle: \"${desc}\"
      url: \"${url}\"
      target: \"_blank\""
    
    log_ok "Discovered: ${title} → ${url}"
  done <<< "$services_json"
  
  # Generate config.yml
  cat > "${data_dir}/config.yml" << EOF
# CloudOS Dashboard — Auto-generated by cloudos module add dashboard
title: "CloudOS"
subtitle: "Personal Cloud"
logo: "https://cdn.jsdelivr.net/npm/@homer/icons/cloud.svg"
header: true
footer: '<p>CloudOS — <a href="https://github.com/Marek-maker/cloudos">GitHub</a></p>'

# Service groups
services:
  - name: "CloudOS Services"
    icon: "https://cdn.jsdelivr.net/npm/@homer/icons/server.svg"
    items:${homer_services}
EOF

  log_ok "Dashboard config generated with discovered services"

  # Start
  log_step "Starting Dashboard..."
  (cd "${module_dir}" && docker compose up -d 2>&1 | tail -3)

  log_ok "Dashboard module running!"
  echo "  Dashboard: http://100.79.173.91:8080"
  echo ""
}
